users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('acceder/', views.login, name='login'),
    path('registro/', views.register, name='register'),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('login/', include('users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/models.py
import uuid

from django.db import models
from django.dispatch import receiver
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_save
from PIL import Image


class Product(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)
    image = models.ImageField(upload_to='products/')
    slug = models.SlugField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.slug


@receiver(pre_save, sender=Product)
def set_slug(sender, instance, *args, **kwargs):
    if instance.title and not instance.slug:
        slug = slugify(instance.title)
        while Product.objects.filter(slug=slug).exists():
            slug = slugify(
                f'{instance.title}-{str(uuid.uuid4())[:8]}'
            )
        instance.slug = slug


@receiver(pre_save, sender=Product)
def set_title(sender, instance, **kwargs):
    if instance.title:
        instance.title = instance.title.capitalize()


@receiver(post_save, sender=Product)
def set_image(sender, instance, *args, **kwargs):
    if instance.image:
        img = Image.open(instance.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(instance.image.path)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group
from django.dispatch import receiver
from django.db.models.signals import post_save


class User(AbstractUser):
    ROLE_CHOICES = {
        ('client', 'Cliente'),
        ('employee', 'Empleado'),
        ('provider', 'Proveedor'),
    }

    role = models.CharField(max_length=50, choices=ROLE_CHOICES)

    REQUIRED_FIELDS = ['email', 'role']

    def get_role(self):
        return getattr(self, self.role, None)


class Client(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Employee(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Provider(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def set_user_rol(sender, instance, **kwargs):
    if kwargs.get('created', False):
        user = instance
        if instance.role == 'client':
            Client.objects.create(user=instance)
            group = Group.objects.get(name='cliente')
            user.groups.add(group)
        elif instance.role == 'employee':
            Employee.objects.cruate(user=instance)
            group = Group.objects.get(name='empleado')
            user.groups.add(group)
        else:
            Provider.objects.create(user=instance)
            group = Group.objects.get(name='proveedor')
            user.groups.add(group)

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm

from .models import (
    User,
)


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username', 'first_name', 'last_name', 'email', 'role'
        ]
        labels = {
            'username': 'Nombre de Usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'email': 'Correo',
            'role': 'Rol'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
            })

products/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

from .models import User
from .forms import UserForm


def login(request):
    template_name = 'users/login.html'
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            messages.success(request, f'Bienvenido {user.username}')
            return redirect('commentaries:commentarie')
        else:
            messages.error(request, 'Usuario o Contraseña incorrectas')

    return render(request, template_name)


def register(request):
    template_name = 'users/register.html'
    form = UserForm(request.POST)
    if request.method == 'POST' and form.is_valid():
        user = form.save()
        if user:
            login(request, user)
            messages.success(
                request, f'El usuario {user.username} fue creado exitosamente')
            return redirect('')

    return render(request, template_name, {
        'form': form,
    })

users/templates/users/base_login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inc</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<body>
    <div class="h-100 container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>

users/templates/users/login.html
{% extends 'users/base_login.html' %}
{% block content %}
<div class="mx-auto d-table h-100 col-sm-10 col-md-8 col-lg-6">
    <div class="d-table-cell align-middle">
        <div class="text-center mt-4">
            <h2>Bienvenido al sistema web</h2>
            <p>Ingresa los datos para iniciar sesion</p>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="m-sm-4">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Nombre de Usuario</label>
                            <input type="text" class="form-control form-control-lg" name="username"
                                placeholder="Ingrese el nombre de Usuario">
                        </div>
                        <div class="form-group">
                            <label>Contraseña</label>
                            <input type="password" class="form-control form-control-lg" name="password"
                                placeholder="Ingrese la Contraseña">
                            <small>
                                <a href="{% url 'users:register' %}">Crear Cuenta</a>
                            </small>
                        </div>
                        <div class="text-center mt-3">
                            <button class="btn btn-lg btn-primary">Ingresar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base_login.html' %}
{% block content %}
    <div class="mx-auto d-table h-100 col-sm-10 col-md-8 col-lg-6">
        <div class="d-table-cell align-middle">
            <div class="text-center mt-4">
                <h2>Bienvenido al sistema web</h2>
                <p>Ingresa los datos para crear su cuenta</p>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="m-sm-4">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                {% for field in form %}
                                    {{ field.label_tag}}
                                    {{ field }}
                                {% endfor %}
                            </div>
                            <small>
                                <a href="{% url 'users:login' %}">Cancelar</a>
                            </small>
                            <div class="text-center mt-3">
                                <button class="btn btn-lg btn-primary">Crear Cuenta</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}